export const teamData = [
  {
    id: 1,
    img: "https://optechanimation1.netlify.app/assets/images/team/team1.png",
    name: "Marvin McKinney",
    role: "CEO & Founder",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  },
  {
    id: 2,
    img: "https://optechanimation1.netlify.app/assets/images/team/team2.png",
    name: "Sophia Rodriguez",
    role: "Creative Director",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  },
  {
    id: 3,
    img: "https://optechanimation1.netlify.app/assets/images/team/team3.png",
    name: "Sophia Rodriguez",
    role: "Lead Developer",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  },
  {
    id: 4,
    img: "https://optechanimation1.netlify.app/assets/images/team/team4.png",
    name: "Alexander Cameron",
    role: "Product Designer",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  },
  {
    id: 5,
    img: "https://optechanimation1.netlify.app/assets/images/team/team5.png",
    name: "Barbara Dundas",
    role: "Digital Marketer",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  },
  {
    id: 6,
    img: "https://optechanimation1.netlify.app/assets/images/team/team6.png",
    name: "Zachary Collins",
    role: "Cyber Specialist",
    linkedin: "#",
    twitter: "#",
    instagram: "#",
  }

]